abc = válido
5peso = não válido porque começa com um número
_valor = válido
Ernesto Costa = não válido porque tem espaços em branco
ABC = válido
with = não válido porque é keyword
peso$ = não válido porque tem $
minha_altura = válido
class = não válido porque é keyword
nome_ALUNO = válido
a(b) = válido
___1 = válido
__x__ = válido
import_from = válido
area-rect = válido